# Generated by Django 5.2 on 2025-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=123)),
                ('last_name', models.CharField(max_length=123)),
                ('first_name', models.CharField(max_length=123)),
            ],
        ),
    ]
