# Generated by Django 5.2 on 2025-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_athlete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Initialization'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='init', max_length=20),
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
    ]
